[decorators]
custom_function = true
another_plugin = true

[parameter_names]
int_keywords = ["count", "index", "number", "size", "total", "quantity", "amount", "position", "capacity", "length", 
                "volume", "weight", "height", "width", "depth", "radius", "distance", "age", "frequency", "rate",
                "score", "level", "rank", "page", "id", "minutes", "hours", "days", "weeks", "months", "years", 
                "attempts", "points", "entries", "occurrences", "iterations", "batches", "samples", "threshold", 
                "max", "min", "average", "sum", "multiplier", "factor"]

str_keywords = ["name", "title", "label", "description", "identifier", "key", "path", "url", "text", "message",
                "content", "filename", "extension", "type", "category", "status", "state", "code", "note", "summary",
                "detail", "query", "command", "input", "output", "password", "email", "username", "address", 
                "city", "country", "zip", "phone", "url", "domain", "hostname", "file", "directory", "folder",
                "token", "id", "uuid", "hash", "timestamp", "date", "time", "datetime", "author", "creator", 
                "version", "tag", "signature", "language", "format", "charset", "encoding"]

bool_keywords = ["is_", "has_", "can_", "should_", "was_", "will_", "contains_", "exists_", "enabled_", "active_", 
                 "checked", "visible", "hidden", "available", "confirmed", "valid", "authenticated", "deleted", 
                 "public", "private", "read_only", "writeable", "required", "optional", "visible", "locked", 
                 "connected", "disconnected", "synced", "loaded", "initialized", "started", "stopped", "paused",
                 "running", "completed", "success", "failed", "error", "ready", "processed"]

[default_values]
int_defaults = ["0", "1", "2", "3", "4", "5", "10", "100", "42", "-1", "99", "1000", "64", "32", "16", "8", 
                "7", "24", "30", "60", "365", "1024", "500", "200", "20", "12", "9", "11", "13", "14", "15"]

float_defaults = ["0.0", "1.0", "2.0", "3.0", "10.5", "100.1", "3.14", "0.5", "0.25", "0.75", "1.5", "2.5", 
                  "100.0", "0.001", "0.01", "0.1", "2.718", "1.618", "6.022", "9.81", "299792458", "0.333", 
                  "0.666", "9.99", "999.99"]

str_defaults = ["''", "'example'", '"example"', '"default"', "'sample'", "'test'", "'none'", "'unknown'", "'n/a'", 
                "'not available'", "'user'", "'admin'", "'guest'", "'default_user'", "'file'", "'path'", "'string'", 
                "'temp'", "'data'", "'config'", "'info'", "'log'", "'error'", "'empty'", "'new'", "'old'", "'temp_file'",
                "'temp_dir'", "'username'", "'password'", "'key'", "'value'", "'option'", "'item'", "'message'",
                "'title'", "'description'", "'label'", "'category'", "'status'", "'state'", "'tag'", "'note'",
                "'summary'", "'detail'", "'content'", "'url'", "'email'", "'phone'", "'address'", "'city'", "'country'"]
